Replace `seq` with POSIX-standard printf(1) in ManyAlternatives test
The test now passes on OpenBSD instead of generating broken source
which was rejected by GHC with

  ManyAlternatives.hs:5:1: error:
      The type signature for ‘f’ lacks an accompanying binding