configure.ac: fix NCG support in --target=
Before this change attempt to build a crosscompiler
on registerised platform (--host=x86_64-pc-linux-gnu)
targeting UNREG platform failed:
    $ ./configure --target=ia64-unknown-linux-gnu

  utils/genapply/../../includes/stg/MachRegs.h:608:2: error:
     #error Cannot find platform to give register info for

The change is to check --target= for NCG availability,
not --host=.

Signed-off-by: Sergei Trofimovich <slyfox@gentoo.org>
(cherry picked from commit cb18447c75e7673d5f57056fbdaa370d11e4c05e)