Improve MonadFail errors by mentioning the pattern
Example error message:

    MonadFailErrors.hs:16:5: error:
        Could not deduce (MonadFail m)
          arising from a do statement
                       with the failable pattern ‘Just x’

Depends on D1248

Reviewers: austin, bgamari

Subscribers: thomie

Differential Revision: https://phabricator.haskell.org/D1489