Expect elf.h as system include
This (hopefully) fixes this error on Darwin:

```
rts/linker/elf_reloc_riscv64.c:6:10: error:
     error: non-portable path to file '"Elf.h"'; specified path differs in case from file name on disk [-Werror,-Wnonportable-include-path]
  |
6 | #include "elf.h"
  |          ^
         ^~~~~~~
         "Elf.h"
```