WIP: T17566
Note that this does *not* work yet, as compiling the test case from
T17566 yields the following inscrutable error:

```
Lib.hs:10:10: error: Couldn't match ‘f’ with ‘f’
   |
10 | class C (f :: kalamity -> Type) z where
   |          ^
```

Yeah. Something is clearly borked.

Rather than try to aimlessly un-bork it, I'll just post my WIP work
here so that Richard and Simon can point out the dumb mistakes I
made.

[ci skip]