rts: fix validate build with gcc 16. `__attribute__((regparm(1)))` is ignored on x86_64 and now gcc warns that it is ignored:
rts/sm/Evac.h:35:1: error:
     error: ‘regparm’ attribute ignored [-Werror=attributes]

See https://gcc.gnu.org/git/?p=gcc.git;a=commit;h=ccead81bbc39668376eb5cf47066acb446cc43f3

Fixes #27366

(cherry picked from commit 9438bec7117433bbc70449d4288f6ee32dbbbec4)