ghci: fix UNREG build (missing fromJust import)
libraries/ghci/GHCi/InfoTable.hsc:249:45: error:
    • Variable not in scope: fromJust :: Maybe EntryFunPtr -> a0
    • Perhaps you meant ‘fromList’ (imported from GHC.Exts)

Signed-off-by: Sergei Trofimovich <siarheit@google.com>

Test Plan: build --enable-unregisterised ghc

Reviewers: simonmar, bgamari, austin

Reviewed By: austin

Subscribers: thomie

Differential Revision: https://phabricator.haskell.org/D1649