Disable warnings for unused goto labels
Clang on OpenBSD aborts compilation with this diagnostics:
```
% "inplace/bin/ghc-stage1" -optc-Wno-error=unused-label -optc-Wall -optc-Werror -optc-Wall -optc-Wextra -optc-Wstrict-prototypes -optc-Wmissing-prototypes -optc-Wmissing-declarations -optc-Winline -optc-Wpointer-arith -optc-Wmissing-noreturn -optc-Wnested-externs -optc-Wredundant-decls -optc-Wno-aggregate-return -optc-fno-strict-aliasing -optc-fno-common -optc-Irts/dist-install/build/./autogen -optc-Irts/include/../dist-install/build/include -optc-Irts/include/. -optc-Irts/. -optc-DCOMPILING_RTS -optc-DFS_NAMESPACE=rts -optc-Wno-unknown-pragmas -optc-O2 -optc-fomit-frame-pointer -optc-g -optc-DRtsWay=\"rts_v\" -static  -O0 -H64m -Wall -fllvm-fill-undef-with-garbage    -Werror -this-unit-id rts -dcmm-lint     -package-env - -i -irts -irts/dist-install/build -Irts/dist-install/build -irts/dist-install/build/./autogen -Irts/dist-install/build/./autogen -Irts/include/../dist-install/build/include -Irts/include/. -Irts/. -optP-DCOMPILING_RTS -optP-DFS_NAMESPACE=rts        -O2 -Wcpp-undef   -Wnoncanonical-monad-instances  -c rts/linker/Elf.c -o rts/dist-install/build/linker/Elf.o

rts/linker/Elf.c:2169:1: error:
     error: unused label 'dl_iterate_phdr_fail' [-Werror,-Wunused-label]
     |
2169 | dl_iterate_phdr_fail:
     | ^
dl_iterate_phdr_fail:
^~~~~~~~~~~~~~~~~~~~~

rts/linker/Elf.c:2172:1: error:
     error: unused label 'dlinfo_fail' [-Werror,-Wunused-label]
     |
2172 | dlinfo_fail:
     | ^
dlinfo_fail:
^~~~~~~~~~~~
2 errors generated.
```

(cherry picked from commit 8961d632f34cffd90594406c697712d9dde4a626)