Draft: Split GHC.Generics into two modules
Most of `GHC.Generics` has now been moved to `GHC.Generics.Internal`, which
`GHC.Generics` re-exports. The only things now defined in `GHC.Generics` are
the derived `Generic(1)` instances. These need to be put in a different module
because of GHC's new approach to dependency analysis, which is perfectly within
its rights to typecheck a derived `Generic` instance before it typechecks any
of the definitions that are referenced in the generated code. Putting the
definitions in a separate module from the derived `Generic` instances is a
sure-fire way to ensure that this doesn't happen.

Unfortunately, this uncovers another issue when building `Cabal-syntax`:

```
libraries/Cabal/Cabal-syntax/src/Distribution/Compat/Prelude.hs:279:21: error: [GHC-88464]
    Variable not in scope: from :: a -> f0 a0
    Suggested fix:
      Add ‘from’ to the import list in the import of ‘GHC.Generics’
      (at libraries/Cabal/Cabal-syntax/src/Distribution/Compat/Prelude.hs:251:1-105).
    |
279 | genericRnf = grnf . from
    |                     ^^^^
```

See https://gitlab.haskell.org/ghc/ghc/-/issues/23496#note_507555.