FixedRuntimeRepError: omit unhelpful explanation
This commit tweaks the FixedRuntimeRepError case of pprTcSolverReportMsg,
to avoid including an explanation which refers to a type variable that
appears nowhere else.

For example, the old error message could look like the following:

  The pattern binding does not have a fixed runtime representation.
  Its type is:
    T :: TYPE R
  Cannot unify ‘R’ with the type variable ‘c0’
  because the former is not a concrete ‘RuntimeRep’.

With this commit, we now omit the last two lines, because the concrete
type variable (here 'c0') does not appear in the type displayed to the
user (here 'T :: TYPE R').