Document in commit message cycle with unpack
- GHC.Internal.CString defines a known-key name unpackCString# (unpackCStringIdKey)
- IIUC, this known-key is looked up essentially for all modules, as long as there’s some literal string in it (coreStringLit uses unpackCStringIdKey)
- GHC.Internal.Types has literal strings, so it needs to lookup unpackCString. It fails with this error:

libraries/ghc-internal/src/GHC/Internal/Types.hs:653:1: error: [GHC-99040]
   • Could not find known-key entity ‘unpackCString#’
       in the top-level environment (unqualified, or qualified as Rebindable)
       Consider importing it
       Call stack:
             lookupKnownGRE, called at compiler/GHC/Iface/Load.hs:196:10 in ghc-10.1-inplace:GHC.Iface.Load
             […]
             tcLookupKnownKeyId, called at compiler/GHC/Tc/Solver/Monad.hs:1192:36 in ghc-10.1-inplace:GHC.Tc.Solver.Monad
   • In the kind ‘k’
     In the class declaration for ‘Coercible’
   |
653 | class Coercible (a :: k) (b :: k)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

- This makes sense, unpackCString must be in scope (this is GHC.Internal.Types, i.e. ghc-internal, i.e. compiled with -frebindable-known-names)
	- For GHC.Internal.Types, unpackCString is looked up to later construct a string expression in `evCallStack`
- Thus, GHC.Internal.Types MUST import unpackCString from GHC.Internal.String
- BUT! GHC.Internal.CString imports GHC.Internal.Types…