Print more info about kinds in error messages
This fixes #24553, where GHC unhelpfully said

  error: [GHC-83865]
    • Expected kind ‘* -> * -> *’, but ‘Foo’ has kind ‘* -> * -> *’

See Note [Showing invisible bits of types in error messages]

(cherry picked from commit b72705e9b2ae5575aef92ede6ff975bbbe43004d)