ci: Use nixpkgs-20.04-darwin channel for darwin toolchain
We are currently seeing a couple of errors on darwin machines after I
bumped the toolchain commit.

```
       last 10 log lines:
       >     from .extern.jaraco.text import yield_lines
       >   File "/private/tmp/nix-build-python3.11-setuptools-69.5.1.drv-0/source/setuptools/_vendor/jaraco/text/__init__.py", line 12, in <module>
       >     from setuptools.extern.jaraco.context import ExceptionTrap
       >   File "/private/tmp/nix-build-python3.11-setuptools-69.5.1.drv-0/source/setuptools/_vendor/jaraco/context.py", line 11, in <module>
       >     import urllib.request
       >   File "/nix/store/z3ccgikilqsd1kzjf1sr03wbnjyga4hh-python3-minimal-3.11.9/lib/python3.11/urllib/request.py", line 2656, in <module>
       >     from _scproxy import _get_proxy_settings, _get_proxies
       > ModuleNotFoundError: No module named '_scproxy'
       >
       > ERROR Backend 'setuptools.build_meta' is not available.
```

In theory this channel should be tested so it should work?