rts: Fix alignment for gen_workspace #26334
After a0fa4941903272c48b050d24e93eec819eff51bd bootstrap is broken on
s390x and errors out with

rts/sm/GCThread.h:207:5: error:
     error: alignment of array elements is greater than element size
      207 |     gen_workspace gens[];
          |     ^~~~~~~~~~~~~

The alignment constraint is applied via the attribute to the type
gen_workspace and leaves the underlying type struct gen_workspace_
untouched.  On Aarch64, x86, and s390x the struct has a size of 128
bytes.  On Aarch64 and x86 the alignments of 128 and 64 are divisors of
the size, respectively, which is why the type is a viable member type
for an array.  However, on s390x, the alignment is 256 and therefore is
not a divisor of the size and hence cannot be used for arrays.

Basically I see two fixes here.  Either decrease the alignment
requirement on s390x, or by applying the alignment constraint on the
struct itself.  The former might affect performance as noted in
a0fa4941903272c48b050d24e93eec819eff51bd.  The latter introduces padding
bits whenever necessary in order to ensure that
sizeof(gen_workspace[N])==N*sizeof(gen_workspace) holds which is done by
this patch.