Ghci environment: Do not remove shadowed ids
previously defined names need to be kept around, e.g. for type
signatures:
```
ghci> data T = T
ghci> let t = T
ghci> data T = T
ghci> :t t
t :: Ghci1.T
```
and indeed they can be used:
```
ghci> let t2 = Ghci1.T :: Ghci1.T
ghci> :t t2
t2 :: Ghci1.T
```

However, previously this did not work for ids (non-types), although they
are still around under the qualified name internally:
```
ghci> let t = "other t"
ghci> t'

<interactive>:8:1: error:
    • Variable not in scope: t'
    • Perhaps you meant one of these:
        ‘Ghci2.t’ (imported from Ghci2), ‘t’ (line 7), ‘t2’ (line 5)
ghci> Ghci2.t

<interactive>:9:1: error:
    • GHC internal error: ‘Ghci2.t’ is not in scope during type checking, but it passed the renamer
      tcl_env of environment: []
    • In the expression: Ghci2.t
      In an equation for ‘it’: it = Ghci2.t
```

This fixes the problem by simply removing the code that tries to remove
shadowed ids from the environment. Now you can refer to shadowed ids using
`Ghci2.t`, just like you can do for data and type constructors. This
simplifies the code, makes terms and types more similar, and also
fixes #20455.