WIP: T17566
Note that this does *not* work yet, as compiling the test case from
T17566 yields the following inscrutable error:

```
Lib.hs:10:1: error:
    • The kind of ‘C’ is ill-scoped
        Inferred kind: C :: forall k kalamity.
                            (kalamity -> *) -> k -> Constraint
      NB: Inferred variables
        (namely: k) always come first
        then Specified variables (namely: kalamity)
      Perhaps try this order instead:
        k kalamity (f :: kalamity -> *) (z :: k)
    • In the class declaration for ‘C’
   |
10 | class C (f :: kalamity -> Type) z where
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...

Lib.hs:11:3: error:
    • The kind of ‘T’ is ill-scoped
        Inferred kind: T :: forall kalamity (f :: kalamity -> *)
                                   (a :: kalamity).
                            f a -> f a
      NB: Inferred variables
        (namely: kalamity) always come first
        then Specified variables
        (namely: (f :: kalamity -> *) (a :: kalamity))
      Perhaps try this order instead:
        kalamity (f :: kalamity -> *) (a :: kalamity) (x :: f a)
    • In the associated type family declaration for ‘T’
   |
11 |   type T (x :: f a) :: f a
   |   ^^^^^^^^^^^^^^^^^^^^^^^^
```

Yeah. Something is clearly borked.

Rather than try to aimlessly un-bork it, I'll just post my WIP work
here so that Richard and Simon can point out the dumb mistakes I
made.

[ci skip]