testsuite: Mark T13702 as requiring share libraries
It fails on statically-built Alpine with
```
T13702.hs:1:1: error:
    Could not find module ‘Prelude’
    Perhaps you haven't installed the "dyn" libraries for package ‘base-4.15.0.0’?
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
  |
1 | {-# LANGUAGE ForeignFunctionInterface #-}
  | ^
```

(cherry picked from commit 852ec4f50fe16d0f47b19603035a34d4520de515)