Fix label type for __stginit_* labels: those are .data labels, not .text
Noticed when was building --enable-unregisterised build for x86_64:

```
  /tmp/ghc22931_0/ghc_3.hc:5:9: error:
       error: '__stginit_ghczmprim_GHCziTypes' redeclared as different kind of symbol
       StgWord __stginit_ghczmprim_GHCziTypes[]__attribute__((aligned(8)))= {
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    |
  5 | StgWord __stginit_ghczmprim_GHCziTypes[]__attribute__((aligned(8)))= {
    |         ^

  In file included from /tmp/ghc22931_0/ghc_3.hc:3:0: error:

  /tmp/ghc22931_0/ghc_3.hc:4:5: error:
       note: previous declaration of '__stginit_ghczmprim_GHCziTypes' was here
       EF_(__stginit_ghczmprim_GHCziTypes);
           ^
```

The error here is mismatch in symbol type: EF_ ("external function")
It should be EC_ ("external closure").

The same build failure does not happen in HEAD because the __stginit_*
is not generated there anymore (see a92ff5d66182d992d02dfaad4c446ad074582368)

Fixes #14009

Signed-off-by: Sergei Trofimovich <slyfox@gentoo.org>