On FreeBSD 12 sys/sysctl.h requires sys/types.h
Else build fails with:

    In file included from ExecutablePath.hsc:42:
    /usr/include/sys/sysctl.h:1062:25: error: unknown type name 'u_int'; did you mean 'int'?
     int sysctl(const int *, u_int, void *, size_t *, const void *, size_t);
			     ^~~~~
			     int
    compiling libraries/base/dist-install/build/System/Environment/ExecutablePath_hsc_make.c failed (exit code 1)

Perhaps also also other FreeBSD releases, but additional include
will no harm even if not needed.