Allow users to disable Unicode with an env var
Unicode renders funny on my terminal and I like to avoid it where
possible. Most applications which print out non-ascii characters allow
users to disable such prints with an environment variable (e.g.
Homebrew).

This diff disables Unicode usage when the environment variable
`GHC_NO_UNICODE` is set. To test, set the env var and compile a bad
program. Note that GHC does not print Unicode bullets but instead prints
out asterisks:

```
$ GHC_NO_UNICODE= _build/stage1/bin/ghc ../Temp.hs
[1 of 1] Compiling Temp             ( ../Temp.hs, ../Temp.o )

../Temp.hs:4:23: error:
    * Couldn't match type `Bool' with `a -> Bool'
      Expected type: Bool -> a -> Bool
        Actual type: Bool -> Bool
    * In the first argument of `foldl', namely `(&& (flip $ elem u))'
      In the expression: foldl (&& (flip $ elem u)) True v
      In an equation for `isPermut':
          isPermut u v = foldl (&& (flip $ elem u)) True v
    * Relevant bindings include
        v :: [a] (bound at ../Temp.hs:4:12)
        u :: [a] (bound at ../Temp.hs:4:10)
        isPermut :: [a] -> [a] -> Bool (bound at ../Temp.hs:4:1)
  |
4 | isPermut u v = foldl (&& (flip $ elem u)) True v
  |                       ^^^^^^^^^^^^^^^^^^
```

(Broken code taken from Stack Overflow)