RetainerProfile.c: include missing header (#8810)
Found by clang:

  rts_dist_HC rts/dist/build/RetainerProfile.p_o

  rts/RetainerProfile.c:1779:5:
     error: implicit declaration of function 'markStableTables' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        markStableTables(retainRoot, NULL);

Signed-off-by: Sergei Trofimovich <slyfox@gentoo.org>
Signed-off-by: Austin Seipp <austin@well-typed.com>