Update process submodule to 1.2.3.0 snapshot
This fixes the compilation failure

  libraries\process\System\Process\Internals.hs:36:5:
      Not in scope: `stopDelegateControlC'
      ...

(however, GHC HEAD skipped process-1.2.2 which has that issue)