Update process submodule to 1.2.3.0 snapshot
This fixes the compilation failure

  libraries\process\System\Process\Internals.hs:36:5:
      Not in scope: `stopDelegateControlC'
      ...

(cherry picked from commit 1def53fec6a6ef985de0e665fede4744dfd456fb)