Testsuite: add -XUndecidableInstances to T3500a
This makes the test pass again with HEAD (7.11), instead of resulting
in:

  T3500a.hs:11:10: error:
      The constraint ‘C (F a)’ is no smaller than the instance head
      (Use UndecidableInstances to permit this)
      In the instance declaration for ‘C (a, b)’

Test Plan: I verified that ghc-6.12.3's typechecker still loops on this
test.

Reviewers: austin, bgamari, simonpj

Reviewed By: simonpj

Subscribers: thomie

Differential Revision: https://phabricator.haskell.org/D1079