docs: Fix code example for NoListTuplePuns
Without the fix, the example produces an error:

  Test.hs:11:3: error: [GHC-45219]
      • Data constructor ‘Tuple’ returns type ‘Tuple2 a b’
          instead of an instance of its parent type ‘Tuple a’
      • In the definition of data constructor ‘Tuple’
        In the data type declaration for ‘Tuple’

Fortunately, a one line change makes it compile.