linker: fix OpenBSD build failure, EM_PPC64 is not defined there
Adam Steen reported build failure on OpenBSD:
  rts/linker/Elf.c:402:0: error:
    error: 'EM_PPC64' undeclared (first use in this function)
      case EM_PPC64: IF_DEBUG(linker,debugBelch( "powerpc64" ));

OpenBSD-6.0 does not define EM_PPC64:
  /usr/include/sys/exec_elf.h:#define EM_PPC 20 /* PowerPC */

Reported-by: Adam Steen <adam@adamsteen.com.au>
Signed-off-by: Sergei Trofimovich <slyfox@gentoo.org>