Remove ANN pragmas in check-ppr and check-exact
This fixes the `devel2+werror` build combo as stage1 does not have TH
enabled.

```
utils/check-exact/Preprocess.hs:51:1: error: [-Werror]
    Ignoring ANN annotations, because this is a stage-1 compiler without -fexternal-interpreter or doesn't support GHCi
   |
51 | {-# ANN module ("HLint: ignore Reduce duplication" :: String) #-}
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```