[testsuite/darwin] fix conc059
This resolves the following:

Compile failed (exit code 1) errors were:
conc059_c.c:27:5: error:
     error: implicitly declaring library function 'exit' with type 'void (int) __attribute__((noreturn))' [-Werror,-Wimplicit-function-declaration]
        exit(0);
        ^
conc059_c.c:27:5: error:
     note: include the header <stdlib.h> or explicitly provide a declaration for 'exit'

(cherry picked from commit 5a6c36ecb41fccc07c1b01fe0f330cd38c2a0c76)