Reject puns in T2T (#24153)
This patch implements pun detection in T2T. Consider:

  x = 42
  f, g :: forall a -> ...
  f (type x) = g x

In accordance with the specification, the `g x` function call is renamed
as a term, so `x` refers to the top-level binding `x = 42`, not to the
type variable binding `type x` as one might expect.

This is somewhat counterintuitive because `g` expects a type argument.
Forbidding puns in T2T allows us to produce a helpful error message:

  Test.hs:5:16: error: [GHC-09591]
    Illegal punned variable occurrence in a required type argument.
    The name ‘x’ could refer to:
      ‘x’ defined at Test.hs:3:1
      ‘x’ bound at Test.hs:5:9

This commit is a follow up to 0dfb1fa799af254c8a1e1045fc3996af2d57a613
where checking for puns was left as future work.